const VIDEO = [
"D:\\Page\\do\\Bánh Mì Chảo Trong Hẻm #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bánh Quẩy Bơm Trứng #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bánh Thịt Trứng #reels #anvat #review #thichanthian .mp4",
"D:\\Page\\do\\Bánh Tráng Trứng Siêu Lầy #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bánh Xốp Phồng (soufflé) #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\BỎNG NGÔ TUỔI THƠ noà! .mp4",
"D:\\Page\\do\\Bột Chiên Đặc Sản Thai Châu #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bột Chiên Full Topping #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bột Chiên Trứng Đường Phố Tây Sơn #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bột Trộn Chua Cay #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Cả nhà đối xử bất công với cậu bé #shorts.mp4",
"D:\\Page\\do\\Cách trị bạn gái ngủ quá giờ trưa =)) #viral #trending.hd.mp4",
"D:\\Page\\do\\Cần tuyển con rể mới =)) #viral #trending.hd.mp4",
"D:\\Page\\do\\Combo quên giã đông và quên bật nút nồi cơm này thì xứng đáng ra đường chơi luôn này.hd.mp4",
"D:\\Page\\do\\Con Mazda 6 cũ rích ấy à =)).hd.mp4",
"D:\\Page\\do\\Cô gái đã nghĩ ra cách thông minh để trốn khỏi lớp #shorts.mp4",
"D:\\Page\\do\\Cô gái đã sốc khi phát hiện đàn kiến trong máy tính #shorts.mp4",
"D:\\Page\\do\\Cô gái giả vờ làm bánh pizza cho chồng và cái kết #shorts.mp4",
"D:\\Page\\do\\Cô gái kêu cứu vì có người đàn ông bám theo #shorts.mp4",
"D:\\Page\\do\\Cô gái ngủ thiếp đi trong lúc xăm hình #shorts.mp4",
"D:\\Page\\do\\Cô giáo bật mí học sinh yêu thích nhất trong chiếc hộp #shorts.mp4",
"D:\\Page\\do\\Cô giáo rất yêu thương học sinh của mình nhưng #shorts.mp4",
"D:\\Page\\do\\Cơm Hộp Thịt Kho #reels #review #anvat #thichanthian #fyp .mp4",
"D:\\Page\\do\\Chàng trai dùng máy cắt tóc để trêu đùa cậu bé #shorts.mp4",
"D:\\Page\\do\\Chàng trai đi ăn từ chối trả hóa đơn và cái kết #shorts.mp4",
"D:\\Page\\do\\Chàng trai làm ma thuật khiến mọi người bối rối #shorts.mp4",
"D:\\Page\\do\\Chàng trai mắc sai lầm khi xăm hình cho khách #shorts.mp4",
"D:\\Page\\do\\Chàng trai ngỡ ngàng khi ăn bánh Oreo #shorts.mp4",
"D:\\Page\\do\\Chàng trai trở nên nổi tiếng vì những bức ảnh #shorts.mp4",
"D:\\Page\\do\\Chiếc ghế mai mối cho các cặp đôi ở công viên #shorts.mp4",
"D:\\Page\\do\\Chú chim cánh cụt hiểu chuyện nhưng #shorts.mp4",
"D:\\Page\\do\\Chú chó có vết đen kỳ lạ trên cổ suốt nhiều tháng #shorts.mp4",
"D:\\Page\\do\\Chúc mọi người năm mới nhận nhiều lì xì như NYM nha. Happy New Year..hd.mp4",
"D:\\Page\\do\\đ Khi con gái tôi ăn hết mọi thứ trong nhà #shorts.mp4",
"D:\\Page\\do\\Đã bảo là không cay rồi mà.hd.mp4",
"D:\\Page\\do\\Đá Bào Trứng Độc Lạ #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Đã là người mình thích thì hỏi ăn cơm chưa vẫn thấy ngọt =)).hd.mp4",
"D:\\Page\\do\\Đã nghiện lại còn ngại nữa sao em #tinhyeu #reel.hd.mp4",
"D:\\Page\\do\\Đâu đâu cũng là anh em =)) Tuy không cùng ngôn ngữ nhưng cùng chung suy nghĩ.hd.mp4",
"D:\\Page\\do\\Đây là cách nhà ảo thuật gia đánh lừa mọi người #shorts.mp4",
"D:\\Page\\do\\Để mình cảm nhận phút giây mình gần bên. Vòng tay cảm ứng dành cho các cặp đôi yêu xa. Chạm để nhớ.hd.mp4",
"D:\\Page\\do\\Định Cho Em Gái Ăn Thanh Cua Tẩm Ớt Và Cái Kết! #mukbang #food #anuong #anvat #shorts (1).mp4",
"D:\\Page\\do\\Định Cho Em Gái Ăn Thanh Cua Tẩm Ớt Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Đố anh em biết cái này dùng để làm gì nè.hd.mp4",
"D:\\Page\\do\\Đồ Ăn Cay Và Nóng 100 Tệ #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Đổi màu thiệt anh em ạ. Anh em áp dụng thử xem sao nhé #tinhyeu #viral #haihuoc #hanhphuc #real.hd.mp4",
"D:\\Page\\do\\Đồng hành từ con số 0, đến khi có tất cả. Mong rằng sau này khi có tất cả chúng ta vẫn còn có nhau.hd.mp4",
"D:\\Page\\do\\Đúng là kẻ ăn không hết người lần chẳng ra. Địa chỉ của bạn ở đâu để anh em tới giúp sức vv.hd.mp4",
"D:\\Page\\do\\Đừng bao giờ cố chêu chọc một con khỉ #shorts.mp4",
"D:\\Page\\do\\Đừng bao giờ để con gái đi học về nhà một mình #shorts.mp4",
"D:\\Page\\do\\Đừng mắc sai lầm chơi bạt nhún cùng bạn bè #shorts.mp4",
"D:\\Page\\do\\Em cao 1m95 là thật#shorts #cosplay #anime.mp4",
"D:\\Page\\do\\Gội một phát – Sạch gàu, sạch bụi, sạch luôn nỗi lo tóc bết #shorts.mp4",
"D:\\Page\\do\\Giáo viên đã cho thấy rửa tay quan trọng đến mức nào #shorts.mp4",
"D:\\Page\\do\\Giấc mơ của chú mèo trở thành hiện thực #shorts.mp4",
"D:\\Page\\do\\Giấc mơ gia nhập quân đội của họ đã tan vỡ chỉ vì #shorts.mp4",
"D:\\Page\\do\\Giờ thì hết ăn nhé =)).hd.mp4",
"D:\\Page\\do\\Hãy cẩn thận trước khi khen ai đó xinh đẹp #shorts.mp4",
"D:\\Page\\do\\Hình ảnh của tôi khi phải vất vả xin những đồng tiền do chính mình làm ra.hd.mp4",
"D:\\Page\\do\\Họ đã vô tình lập một kỷ lục khi nhảy dây #shorts.mp4",
"D:\\Page\\do\\Hóa ra thứ em yêu chỉ là mái tóc của tôi mà thôi.hd.mp4",
"D:\\Page\\do\\Hoa Tuyết Sen Ngàn Năm #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Hướng Dẫn Ăn Chân Gà Ủ Cay Cho Đúng Cách! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Hướng Dẫn Cách Ăn Chân Gà Kiểu Mới Cực Thú Vị! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Kẻ hủy diệt trái tim anh em FA =)).hd.mp4",
"D:\\Page\\do\\Khi Có Anh Người Yêu Tốt Bụng Và Cái Kết Bất Ngờ! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Khi Chờ Mì Chín Nên Ăn Tạm Món Gì Trước! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Khi Miến Cay Ăn Mãi Mà Không Hết Thì Phải Làm Sao! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Khi tôi biết em gái tôi đi chơi với bạn trai nên tôi thiết kế luôn cho em ấy bộ đồ siêu xinh.hd.mp4",
"D:\\Page\\do\\Khoai Tây Cháy Vân Nam #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Khoai Tây Chiên Quý Châu #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Khoai Tây Chiên Xúc Xích #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Khoai Tây Full Topping #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Khoai Tây Túi Trứng #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Lần này bị tắt loa rồi #xuhuong #tinhyeu #hanhphuc #viral #real #haihuoc.hd.mp4",
"D:\\Page\\do\\Lần này thì bất ngờ thật nha #Real #viral #tinhyeu #short.hd.mp4",
"D:\\Page\\do\\Lần sau nói sớm hơn chút được không vậy.hd.mp4",
"D:\\Page\\do\\Lem Khổng Lồ 100 Tệ #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Lỗi của mình là có vợ quá xinh.hd.mp4",
"D:\\Page\\do\\Lúc Đầu Chê Miến Cay Dở Lúc Sau Lại Định Ăn Vụng! #mukbang #food #anuong #anvat #shorts (1).mp4",
"D:\\Page\\do\\Lúc Đầu Chê Miến Cay Dở Lúc Sau Lại Định Ăn Vụng! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Mì Chua Cay Trùng Khánh #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Gà Tây #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Gà Tây Phô Mai Nướng #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\mì gói trung quốc cay cỡ nào #shorts #anuong #mukbang #thánhăn #tiktok #xuhuong.mp4",
"D:\\Page\\do\\Mì Lạnh Siêu Cay #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Ống Sơn Tây #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Tâm Trạng Đáng Yêu #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Xào Tây Bắc #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mì Xào Truyền Thống #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Mọi người đều nghĩ họ ngồi ở sân vận động nhưng #shorts.mp4",
"D:\\Page\\do\\Mọi người sợ hãi khi đang đi thang máy #shorts.mp4",
"D:\\Page\\do\\Mọi người tò mò bên trong của con tinh linh này #shorts.mp4",
"D:\\Page\\do\\Mọi tuyệt chiêu của nàng đều bị ta khắc chế, chỉ riêng lệ nàng đổ là ta đành chịu thua #hanhphuc #real #viral #haihuoc #xuhuong #tinhyeu.hd.mp4",
"D:\\Page\\do\\Môn thể thao có độ chính xác cao nhất thế giới #shorts.mp4",
"D:\\Page\\do\\Một kẻ đã đuổi theo khi người đàn ông đang quay video #shorts.mp4",
"D:\\Page\\do\\Mua Lego ở chợ đồ cũ phần 2 #namdireview.mp4",
"D:\\Page\\do\\Mua tất cả lego ở chợ đồ cũ #review.mp4",
"D:\\Page\\do\\Muốn uống nước thì nói một câu anh đi lấy liền. Cần gì phải phức tạp thế đâu em.hd.mp4",
"D:\\Page\\do\\Nể phục kĩ năng của mẹ tôi ghê.hd.mp4",
"D:\\Page\\do\\Người đàn ông cố gắng phá tổ ong bằng lửa #shorts.mp4",
"D:\\Page\\do\\Người đàn ông đánh bắt được sinh vật quý hiếm #shorts.mp4",
"D:\\Page\\do\\Người đàn ông khiến bất kỳ ai ngủ chỉ bằng một cú chạm #shorts.mp4",
"D:\\Page\\do\\Người đàn ông phát hiện một con hổ khi mở cửa #shorts.mp4",
"D:\\Page\\do\\Người đàn ông theo đuổi nghệ thuật vì bị đuổi học #shorts.mp4",
"D:\\Page\\do\\Người lính rèn luyện khả năng nín thở dưới bùn #shorts.mp4",
"D:\\Page\\do\\Người mẹ đã dạy con mình cách bò từ món đồ chơi #shorts.mp4",
"D:\\Page\\do\\Người thợ đã mắc sai lầm khi cắt tóc cho khách #shorts.mp4",
"D:\\Page\\do\\Nhà hàng có quy định kỳ lạ khi thực khách đến ăn #shorts.mp4",
"D:\\Page\\do\\Nhà hàng này đã lừa dối khách của mình #shorts.mp4",
"D:\\Page\\do\\Nhây vl =)) Lừa cả bạn bè luôn mà.hd.mp4",
"D:\\Page\\do\\Quên mất là vợ mình ăn được chua.hd.mp4",
"D:\\Page\\do\\Review Blind Box Labubu 2 #chireviewdochoi #blindbox #labubu.mp4",
"D:\\Page\\do\\Review Đồ Chơi Capybara Co Giãn-Review of Elastic Capybara Toys #chireviewdochoi #dochoi #rewiewtoys.mp4",
"D:\\Page\\do\\Review Đồ Chơi Khủng Long Trút Giận-Review of Dinosaur Toys to vent their anger #chireviewdochoi.mp4",
"D:\\Page\\do\\Review đồ chơi xe bán kem #chireviewdochoi #dochoi #short #fyp.mp4",
"D:\\Page\\do\\Review Kem Mịn Da Tay-Review Hand Smoothing Cream #chireviewdochoi #dochoi #rewiewtoys #toys.mp4",
"D:\\Page\\do\\REVIEW SON INTO YOU #shorts #trending #makeup #makeuptutorial #review.mp4",
"D:\\Page\\do\\Review Túi Mù Kiểu Mới-Review New Blind Bag #chireviewdochoi #dochoi #rewiewtoys #toys #viralvideo.mp4",
"D:\\Page\\do\\Review Vòng Tay Màu Tự Làm-Review of DIY Colored Bracelets #chireviewdochoi #dochoi #rewiewtoys#toys.mp4",
"D:\\Page\\do\\Sushi Đường Phố #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Sự Khác Biệt Giữa Người Ăn Kiêng Và Người Ăn Khỏe! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Sự Khác Biệt Giữa Người Sợ Béo Và Không Sợ Béo! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Sự Khác Biệt Giữa Người Thường Và Người Sành Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
"D:\\Page\\do\\Tai Nghe Bluetooth #review #thichanthian #fyp #tainghebluetooth #tainghechuptai .mp4",
"D:\\Page\\do\\Tiệm Cơm Dưới Nhà #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Tiệm Trà Chanh Em Gái LOLITA #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Tình yêu của hai chú kiến giữa những con sóng #shorts.mp4",
"D:\\Page\\do\\Tôi thấy ẻm hát hay vs cute vãi chưởng luôn mà.hd.mp4",
"D:\\Page\\do\\Tự chui đầu vào rọ là có thật =)).hd.mp4",
"D:\\Page\\do\\Thạch Đạu Dưa 35 Năm #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Thạch Đậu Cay #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Theo Chân Tiểu Bạch 1 #reels #funny #haihuoc #vuinhon #xh #thichanthian #fyp .mp4",
"D:\\Page\\do\\Theo Chân Tiểu Bạch 2 #reels #funny #haihuoc #vuinhon #xh #thichanthian #fyp .mp4",
"D:\\Page\\do\\Thích ai nhớ nói ra nhé mọi người kẻo sau hối tiếc lắm.hd.mp4",
"D:\\Page\\do\\Thịt Bò Gác Bếp #reels #review #anvat #thichanthian #fyp .mp4",
"D:\\Page\\do\\Thịt Heo Cháy Trùng Khánh #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Thử Thách Ăn Sập Chợ Với 50 Tệ #reels #anvat #review #thichanthian #fyp #thuthachanuong .mp4",
"D:\\Page\\do\\Thử thách nhảy dây cùng các đồng đội #shorts.mp4",
"D:\\Page\\do\\Trong mắt vợ tôi luôn là con của cô ấy.hd.mp4",
"D:\\Page\\do\\Trứng Bắc Thảo Trộn Siêu Cay #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Trứng Cuộn Xúc Xích Siêu Ngon #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Trước và sau khi thấy người yêu nhìn khác hẳn luôn nhì.hd.mp4",
"D:\\Page\\do\\Vieview Blind Box Labubu Toys #chireviewdochoi #blindbox #labubu #toys #rewiewtoys.mp4",
"D:\\Page\\do\\Xiên Chiên 20 Năm Tuổi #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Xiên Chiên Siêu Ngon #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Xin cách dỗ người yêu hiệu quả đi! Không thì toang mất!.hd.mp4",
"D:\\Page\\do\\Xôi Nếp quá rẻ #reels #anvat #review #thichanthian #fyp #.mp4",
"D:\\Page\\do\\Xúc Xích Chiên Phô Mai #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\10 điểm uy tín luôn =)).hd.mp4",
"D:\\Page\\do\\7472353620764282123-注水刹那，云雾在杯中舒展， 兰花香沁心，回甘似山泉淌过舌尖。生态茶，喝的不仅是健康，更是云雾缭绕的山水画卷，是匠人掌心传递的生命温度。#召唤茶友 #户外#艺术在抖音#春茶原来这么香……版本过低，升级后可展示全部信息.mp4",
"D:\\Page\\do\\Anh chàng đã quên mật khẩu điện thoại của mình #shorts.mp4",
"D:\\Page\\do\\Anh em nào muốn được vợ hay bạn gái kéo ghế cho thì áp dụng ngay nhé.hd.mp4",
"D:\\Page\\do\\Anh em nào nóng giận thì nhìn màu xanh xem có hết nóng giận không nhé.hd.mp4",
"D:\\Page\\do\\Anh em nào xin đi chơi điện tử nhưng vợ không cho thì áp dụng ngay nhé.hd.mp4",
"D:\\Page\\do\\Bábh Sốt Mè Đậu Nành #reels #anvat #review #thichanthian #fyp .mp4",
"D:\\Page\\do\\Bài kiểm tra để trở thành tiếp viên hàng không #shorts.mp4",
];
const CAPTION = [
    '"Đẹp 𝗇𝗁𝗎̛́𝖼 𝖼𝖺́𝗂 𝗇𝖺́𝖼𝗁 chị em ơi" https://s.shopee.vn/3LCT9ST5fB'
]
module.exports = {
    CAPTION, VIDEO
};