const VIDEO = [
    "D:\\Page\\b\\Vừa Nấu Ăn Cùng Chồng Vừa Buôn Điện Thoại Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\XIÊN QUE TRƯỚC CỔNG TRƯỜNG GIÁ SIÊU RẺ #food.mp4",
    "D:\\Page\\b\\1.mp4",
    "D:\\Page\\b\\2.mp4",
    "D:\\Page\\b\\3.mp4",
    "D:\\Page\\b\\4.mp4",
    "D:\\Page\\b\\5.mp4",
    "D:\\Page\\b\\6.mp4",
    "D:\\Page\\b\\7.mp4",
    "D:\\Page\\b\\8.mp4",
    "D:\\Page\\b\\9.mp4",
    "D:\\Page\\b\\10.mp4",
    "D:\\Page\\b\\11.mp4",
    "D:\\Page\\b\\12.mp4",
    "D:\\Page\\b\\13.mp4",
    "D:\\Page\\b\\14.mp4",
    "D:\\Page\\b\\15.mp4",
    "D:\\Page\\b\\16.mp4",
    "D:\\Page\\b\\17.mp4",
    "D:\\Page\\b\\Cuộc Sống Của Anh Chồng Sợ Vợ Sẽ Như Thế Nào! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cuộc Thi Ai Ăn Chậm Sẽ Phải Trả Tiền Ăn Cả Nhóm! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cuộc Thi Ai Ăn Chậm Thì Phải Rửa Bát Đũa! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cuộc Thi Ai Ăn Chậm Thì Phải Trả Tiền Ăn Cả Nhóm! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cuộc Thi Ai Ăn Chậm Thì Sẽ Phải Rửa Bát Đũa! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cuộc Thi Ai Ăn Chậm Thì Sẽ Phải Rữa Bát Đũa! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\CHIẾC BÁNH -TÌNH BẠN- (1).mp4",
    "D:\\Page\\b\\CHIẾC BÁNH -TÌNH BẠN-.mp4",
    "D:\\Page\\b\\Chiếc Bút Thần Kì Vẽ Gì Đều Biến Thành Thật! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cho Bạn Gái Ăn Mực Siêu Cay Để Xem Da Mặt Có Đẹp Không! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Cho Mù Tạt Vào Trứng Làm Chồng Ăn Cay Phát Khóc! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Chơi Bạn Thích Ai Lại Bị Vợ Phát Hiện Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Chơi Trò Chơi Bịt Mắt Tìm Đồ Ăn Vặt Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Chơi Trò Chơi Chọn Phải Món Gì Thì Ăn Món Đó! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Chơi Trò Chơi Đoán Đúng Thưởng Chân Gà Ủ Cay! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Chơi Trò Chơi Oẳn Tù Xì Thưởng Bánh Sandwich! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Dùng Bánh Kem Để Troll Chồng Tức Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Dùng Kẹo Sô Cô La Để Giải Cứu Người Khỏi Kẻ Xấu! #mukbang #food #anuong #anvat #shorts (1).mp4",
    "D:\\Page\\b\\Dùng Rong Biển Giả Làm Tóc Chêu Đùa Chồng Tức Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Dùng Rong Biển Làm Tóc Giả Chêu Đùa Chồng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Dùng Rong Biển Sợi Giả Làm Tóc Để Chêu Đùa Chồng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Định Cho Mù Tạt Vào Miến Của Vợ Và Cái Kết Đắng! #mukbang #food #anuong #anvat #shorts (1).mp4",
    "D:\\Page\\b\\Định Cho Mù Tạt Vào Miến Của Vợ Và Cái Kết Đắng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Định Lừa Vợ Để Có Bánh Ngọt Ăn Và Cái Kết Đắng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Định Lừa Vợ Để Có Bánh Ngọt Ăn Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Đúng Là Hảo Cô Gái Tốt Ai Mà Quen Thì Thật Có Phúc! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Gái Xinh Thì Cũng Không Thể Bằng Bánh Sandwich! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Giả Vờ Bị Cắn Biến Thành Zombie Dọa Chồng Sợ Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hiểu Nhầm Bị Ăn Trực Bánh Sandwich Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Kiểu Mới Cực Kì Ngon Miệng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ủ Cay Cho Đúng Cách! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ủ Cay Sao Cho Đúng Cách Nhất! #mukbang #food #anuong #anvat #shorts (1).mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ủ Cay Sao Cho Đúng Cách Nhất! #mukbang #food #anuong #anvat #shorts (2).mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ủ Cay Sao Cho Đúng Cách Nhất! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ủ Cay Sao Cho Đúng Cách! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Ăn Chân Gà Ướp Chanh Sao Cho Đúng Cách! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Chân Gà Kiểu Mới Cực Thú Vị! #mukbang #food #anuong #anvat #shorts (1).mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Chân Gà Kiểu Mới Cực Thú Vị! #mukbang #food #anuong #anvat #shorts (2).mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Chân Gà Kiểu Mới Cực Thú Vị! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Mì Cay Kiểu Mới Cực Thú Vị! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Mì Cay Kiểu Mới Siêu Tiết Kiệm! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Ăn Mì Cay Siêu Tiết Kiệm! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Làm Mì Lạnh Chân Gà Cực Độc Lạ! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Trộm Tiền Của Vợ Để Đi Ăn Đồ Vặt! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Cách Trộm Tiền Của Vợ Và Cái Kết Đắng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Hướng Dẫn Nấu Mì Thập Cẩm Cay Sao Cho Đúng Cách! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Ăn Mì Siêu Cay Mãi Không Hết Thì Phải Làm Sao! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Bạn Định Ăn Măng Cay Nhưng Vợ Bạn Lại Quá Phiền! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Bạn Được Vợ Đút Cho Ăn Chân Gà Bạn Sẽ Làm Gì! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Có Anh Người Yêu Ga Lăng Và Cái Kết Bất Ngờ! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Có Cô Vợ Cá Tính Ham Ăn Sẽ Như Thế Nào! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi có người hỏi tuổi của bạn.mp4",
    "D:\\Page\\b\\Khi Chồng Nhờ Tôi Cất Giúp Chân Gà Ủ Cay Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Chờ Cho Mì Cay Chín Nên Ăn Tạm Món Gì! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Đang Làm Bất Cứ Việc Gì Cũng Ăn Chân Gà Ủ Cay! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Mì Siêu Cay Ăn Mãi Mà Không Hết Thì Phải Làm Sao! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Nhờ Chồng Quay Giúp Video Ăn Chân Gà Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Quen Mồm Chê Đồ Ăn Vợ Nấu Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Tôi Mới Mua Chân Gà Định Để Dành Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Khi Tôi Vừa Mua Bánh Mochi Định Để Dành Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Làm Ảo Thuật Biến Quả Trứng Thành Các Món Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Làm Ảo Thuật Để Lừa Bánh Trung Thu Của Vợ! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Làm Ảo Thuật Lừa Vợ Để Có Bánh Ngọt Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Làm Giả Bánh Kem Chêu Đùa Làm Vợ Tức Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Làm Giả Bánh Sôcôla Troll Cô Vợ Tức Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Lẩu ở Trung Quốc.mp4",
    "D:\\Page\\b\\Lỡ Tay Làm Mất Viên Ngọc Quý Của Mẹ Và Cái Kết! #haihuoc #vuinhon #troll #funny #shorts.mp4",
    "D:\\Page\\b\\Lừa Cô Bạn Thân Để Có Bánh Ngọt Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Lừa Vợ Để Có Bánh Ngọt Ăn Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Mì Cay Ăn Mãi Mà Không Hết Thì Phải Làm Sao! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Mì cay Trung Quốc.mp4",
    "D:\\Page\\b\\MÌ GÀ CAY QUÝ CHÂU #food.mp4",
    "D:\\Page\\b\\MÓN ĐIỂM TÂM TRUYỀN THỐNG CỦA TRUNG QUỐC #food.mp4",
    "D:\\Page\\b\\Món mì cay ăn đẳng cấp quá..mp4",
    "D:\\Page\\b\\Một Ngày Của Bà Mẹ Bầu Sẽ Như Thế Nào! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Một Tình Yêu Thật Đẹp Bắt Đầu Từ Quả Trứng Kho! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Mời Cô Bạn Thân Ăn Thử Que Siêu Cay Và Cái Kết Đắng! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\MỲ BÒ TRÙNG KHÁNH #food.mp4",
    "D:\\Page\\b\\Nơi Tình Yêu Bắt Đầu Từ Một Quả Trứng Kho! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Nhắc Người Yêu Ăn Kiểu Thục Nữ Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Nhất Định Không Ăn Chung Xúc Xích Vì Chê Vợ Mồm Thúi! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Nhờ Chồng Quay Giúp Video Ăn Chân Gà Ủ Cay Và Cái Kết! #mukbang #food #anuong #anvat ##shorts.mp4",
    "D:\\Page\\b\\Những Phản Ứng Khác Nhau Khi Ăn Cổ Vịt Ướp Cay! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Phải Làm Gì Khi Miến Cay Ăn Mãi Mà Không Hết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\REVIEW ĐỒ ĂN NHẬT BẢN #food #foodshorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Của Người Bình Thường Và Người Sành Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Con Trai Và Con Gái Khi Ăn Chân Gà! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Học Sinh Ngoan Và Học Sinh Hư! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Khi Còn Chân Gà Và Khi Đã Ăn Hết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Mẹ Và Tôi Khi Ăn Thử Sữa Chua Hạt! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Người Ăn Kiêng Và Người Ăn Khỏe! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Người Bình Thường Và Người Sành Ăn! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Giữa Người Sành Ăn Và Người Bình Thường! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Khi Còn Chân Gà Và Khi Đã Ăn Hết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Sự Khác Biệt Khi Chồng Ăn No Và Khi Vợ Ăn No! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Tiểu Hân lần đầu đi ăn đồ ăn nhanh #shorts.mp4",
    "D:\\Page\\b\\Tư vấn tình cảm cho bạn thân.mp4",
    "D:\\Page\\b\\Thánh ăn thịt mỡ Trung Quốc hot tiktok -- Mukbang Chinese.mp4",
    "D:\\Page\\b\\Thi Xem Ai Ăn Cay Hơn Ai Và Cái Kết Xấu Hổ! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Thử Tài Thám Tử Cùng Tìm Xem Ai Đã Ăn Vụng Cánh Gà Cay! #mukbang #food #anuong #anvat #shorts (1).mp4",
    "D:\\Page\\b\\Thử Tài Thám Tử Cùng Tìm Xem Ai Đã Ăn Vụng Thanh Cua! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Thử Thách Ăn Hết Đĩa Sụn Ướp Cay Trong Vòng 30 Giây! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Bịt Mặt Tìm Đồ Ăn Vặt Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Gia Đình Chọn Đồ Gì Để Tránh Bị Ướt Người! #haihuoc #vuinhon #troll #funny #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Gia Đình Chọn Đồ Gì Để Tránh Ướt Người! #haihuoc #vuinhon #troll #funny #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Gia Đình Chọn Món Gì Uống Món Đó! #haihuoc #vuinhon #troll #funny #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Gia Đình Uống Thử Rồi Đoán Tên Có Thưởng! #haihuoc #vuinhon #troll #funny #shorts.mp4",
    "D:\\Page\\b\\Trò Chơi Vừa Ăn Chân Gà Vừa Mỉm Cười Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Vì Có Cua Ướp Cay Nên Giúp Ba Phát Hiện Bí Mật Của Mẹ! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Vì Lo Giữ Bánh Sandwich Bị Mất Điện Thoại Mà Không Biết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Vừa Ăn Chân Gà Ủ Cay Vừa Chêu Đùa Chồng Sợ Khóc Thét! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Vừa Buôn Điện Thoại Vừa Nấu Ăn Và Cái Kết! #mukbang #food #anuong #anvat #shorts.mp4",
    "D:\\Page\\b\\Vừa Nấu Ăn Cùng Chồng Vừa Buôn Điện Thoại Và Cái Kết! #mukbang #food #anuong #anvat #shorts (1).mp4",
]

const CAPTION = [
    "Khám phá những món ăn vặt 'Ngon quên lối về, Ăn là mê' tại đây 🍴✨ https://cobexinhxan.vercel.app",
    "Tổng hợp món ăn vặt 'Ngon tê tái, Ăn hoài không chán' tại đây 🍕🔥 https://cobexinhxan.vercel.app",
    "Những món ăn vặt 'Ngon hết nấc, Ăn là ghiền' đang chờ bạn tại 🍟❤️ https://cobexinhxan.vercel.app",
    "Săn lùng món ăn vặt 'Ngon đến phát khóc, Ăn xong chỉ muốn khóc thêm' tại đây 🍔😢 https://cobexinhxan.vercel.app",
    "Danh sách món ăn vặt 'Ngon hết nước chấm, Ăn xong xin thêm nước để chấm tiếp' tại đây 🥟💦 https://cobexinhxan.vercel.app",
    "Top món ăn vặt 'Ngon quên cả crush, Ăn xong crush cũng quên luôn mình' chỉ có tại 🍰💔 https://cobexinhxan.vercel.app",
    "Những món ăn vặt 'Ngon muốn đội quần, Ăn xong chỉ muốn tìm thêm quần để đội' tại đây 🍭😂 https://cobexinhxan.vercel.app",
    "Món ăn vặt ngon đến mức crush của bạn phải chạy theo xin ăn ké, xem ngay tại 🍩🏃‍♂️ https://cobexinhxan.vercel.app!",
    "Cảnh báo: Những món ăn vặt này ngon quá, ăn xong bạn sẽ quên luôn đường về nhà, xem tại ⚠️🍤 https://cobexinhxan.vercel.app!",
    "Bạn đã sẵn sàng để ăn vặt mà quên luôn cả crush chưa? Click vào 🍡❓ https://cobexinhxan.vercel.app để thử thách bản thân!",
    "Coi chừng nghiện: Món ăn vặt này ngon đến mức bạn sẽ muốn ngủ luôn với nó, click 🍫😴 https://cobexinhxan.vercel.app để xem ngay!",
    "Không click là hối hận: Món ăn vặt ngon đến mức bạn sẽ muốn mở tiệc sinh nhật cho nó, tại 🎂🎉 https://cobexinhxan.vercel.app!",
    "Đừng để dạ dày buồn: Món ăn vặt ngon thế này mà bỏ lỡ thì tiếc lắm, click ngay 🍜😞 https://cobexinhxan.vercel.app!",
    "Bạn có dám thử món ăn vặt ngon đến mức khiến bạn quên cả ngày sinh nhật mình không? Xem tại 🍦🎈 https://cobexinhxan.vercel.app!",
    "Click ngay để biết món ăn vặt ngon đến mức bạn sẽ muốn bỏ hết deadline để ăn, tại 🍳⏰ https://cobexinhxan.vercel.app!",
    "Đừng để cuộc đời thiếu vị: Món ăn vặt ngon thế này mà bỏ qua thì phí lắm, click ngay 🌮🌟 https://cobexinhxan.vercel.app!",
    "Đừng để dạ dày buồn thiu: Món ăn vặt ngon thế này mà bỏ lỡ thì xót lắm, click ngay 🍝😢 https://cobexinhxan.vercel.app!",
    "Đừng để bụng đói kêu gào: Món ăn vặt ngon thế này mà không ăn thì tội lắm, click ngay 🍗📣 https://cobexinhxan.vercel.app!",
    "Đừng để cuộc đời thiếu ngon: Món ăn vặt thế này mà không thử thì phí cả kiếp, click ngay 🍮🌍 https://cobexinhxan.vercel.app!"
];

module.exports = {
    CAPTION, VIDEO
};